import React from "react";
import Link from "next/link";
const Home = () => {
  return (
    <div className="dhiwise-navigation">
      <h1>Homepage</h1>
      <p className="headline">
        This project was generated By{" "}
        <a href="https://www.dhiwise.com">Dhiwise</a>. Quickly use below links
        to navigate through all pages.
      </p>
      <ul>
        <li>
          <Link href="/cart">Cart</Link>
        </li>
        <li>
          <Link href="/homepage">Homepage</Link>
        </li>
        <li>
          <Link href="/shop">Shop</Link>
        </li>
        <li>
          <Link href="/shopdetaildescription">ShopDetailDescription</Link>
        </li>
        <li>
          <Link href="/detailreview">DetailReview</Link>
        </li>
        <li>
          <Link href="/checkout">Checkout</Link>
        </li>
        <li>
          <Link href="/wishlist">Wishlist</Link>
        </li>
        <li>
          <Link href="/team">Team</Link>
        </li>
        <li>
          <Link href="/blog">Blog</Link>
        </li>
        <li>
          <Link href="/blogdetail">BlogDetail</Link>
        </li>
        <li>
          <Link href="/contactus">Contactus</Link>
        </li>
        <li>
          <Link href="/aboutus">Aboutus</Link>
        </li>
      </ul>
    </div>
  );
};
export default Home;
