import React from "react";

import Footer1 from "../../components/Footer1";
import Header1 from "../../components/Header1";
import {
  Image,
  Flex,
  Heading,
  Container,
  Button,
  Text,
  Box,
  Center,
} from "@chakra-ui/react";

export default function EduviJoinAsTeacherPage() {
  return (
    <Flex bg="gray.100" w="100%" direction="column" align="center">
      <Flex gap="48px" w="100%" direction="column" align="center">
        <Header1 bg="gray.100" w="100%" display="flex" />
        <Container
          gap="8px"
          bg="yellow.100"
          w="100%"
          display="flex"
          flexDirection="column"
          alignItems="start"
          justifyContent="flex-start"
          maxW="1280px"
          p="25px"
          borderRadius="20px"
        >
          <Text color="black.900" fontWeight={500}>
            Home | Become An Instructor
          </Text>
          <Flex ml="4px" w="100%" justify="space-between" align="center">
            <Heading size="2xl" as="h1" fontWeight={600}>
              Join Educatsy as
              <br />a Mentor
            </Heading>
            <Box h="201px" w="25%" position="relative">
              <Box h="201px" w="100%" m="auto">
                <Box h="201px" w="100%" position="absolute" m="auto">
                  <Box h="201px" w="100%" m="auto">
                    <Box h="201px" w="100%" m="auto">
                      <Box h="201px" w="100%" m="auto">
                        <Box h="201px" w="100%" m="auto">
                          <Box h="201px" w="100%" m="auto">
                            <Box h="201px" w="100%" m="auto">
                              <Box h="201px" w="100%" m="auto">
                                <Box h="201px" w="100%" m="auto">
                                  <Box h="201px" w="100%" m="auto">
                                    <Box h="201px" w="100%" m="auto">
                                      <Box h="201px" w="100%" m="auto">
                                        <Box
                                          h="201px"
                                          w="100%"
                                          position="absolute"
                                          left="0px"
                                          bottom="0px"
                                          right="0px"
                                          top="0px"
                                          justifyContent="center"
                                          m="auto"
                                        >
                                          <Box h="201px" w="100%" m="auto">
                                            <Box
                                              h="200px"
                                              w="100%"
                                              position="absolute"
                                              left="0px"
                                              bottom="0px"
                                              right="0px"
                                              top="0px"
                                              justifyContent="center"
                                              m="auto"
                                            >
                                              <Image
                                                src="images/img_vector_amber_200.svg"
                                                h="200px"
                                                m="auto"
                                              />
                                              <Image
                                                src="images/img_vector_gray_800_01.svg"
                                                h="14px"
                                                position="absolute"
                                                top="21%"
                                                right="47%"
                                                m="auto"
                                              />
                                              <Image
                                                src="images/img_vector_gray_500_02_10x1.svg"
                                                h="10px"
                                                position="absolute"
                                                bottom="25%"
                                                right="37%"
                                                m="auto"
                                              />
                                            </Box>
                                            <Flex
                                              w="59%"
                                              direction="column"
                                              position="absolute"
                                              right="15%"
                                              bottom="0%"
                                              m="auto"
                                            >
                                              <Flex
                                                ml="68px"
                                                w="2%"
                                                direction="column"
                                                align="start"
                                              >
                                                <Image
                                                  src="images/img_vector_gray_800_01_1x2.svg"
                                                  h="1px"
                                                  w="2px"
                                                />
                                                <Image
                                                  src="images/img_vector_gray_800_01_1x2.svg"
                                                  h="1px"
                                                  w="1px"
                                                />
                                                <Image
                                                  src="images/img_vector_gray_800_01_1x1.svg"
                                                  h="1px"
                                                  w="1px"
                                                />
                                              </Flex>
                                              <Flex
                                                gap="7px"
                                                w="100%"
                                                align="end"
                                              >
                                                <Image
                                                  src="images/img_group_red_300_01.svg"
                                                  h="138px"
                                                />
                                                <Image
                                                  src="images/img_vector_gray_500_02_13x5.svg"
                                                  h="13px"
                                                  mb="50px"
                                                />
                                                <Flex
                                                  h="92px"
                                                  mt="45px"
                                                  bgImage="url(/images/img_group_76.svg)"
                                                  bgSize="cover"
                                                  bgRepeat="no-repeat"
                                                  w="36%"
                                                  direction="column"
                                                  align="end"
                                                  justify="flex-end"
                                                  p="20px"
                                                >
                                                  <Flex
                                                    mt="28px"
                                                    mb="12px"
                                                    w="75%"
                                                    direction="column"
                                                    align="start"
                                                  >
                                                    <Flex
                                                      w="100%"
                                                      justify="space-evenly"
                                                      align="center"
                                                    >
                                                      <Image
                                                        src="images/img_vector_black_900_4x5.svg"
                                                        h="4px"
                                                        w="5px"
                                                      />
                                                      <Image
                                                        src="images/img_vector_black_900_4x5.svg"
                                                        h="2px"
                                                        w="1px"
                                                      />
                                                      <Image
                                                        src="images/img_vector_black_900_3x7.svg"
                                                        h="3px"
                                                      />
                                                    </Flex>
                                                    <Image
                                                      src="images/img_vector_black_900_5x5.svg"
                                                      h="5px"
                                                      w="5px"
                                                    />
                                                  </Flex>
                                                </Flex>
                                              </Flex>
                                            </Flex>
                                          </Box>
                                          <Flex
                                            gap="11px"
                                            w="98%"
                                            direction="column"
                                            position="absolute"
                                            bottom="0%"
                                            right="0px"
                                            left="0px"
                                            m="auto"
                                          >
                                            <Image
                                              src="images/img_vector_gray_400_5x16.svg"
                                              h="5px"
                                              ml="146px"
                                            />
                                            <Image
                                              src="images/img_group_black_900.svg"
                                              h="1px"
                                            />
                                          </Flex>
                                        </Box>
                                        <Image
                                          src="images/img_group_blue_gray_900_02.svg"
                                          h="44px"
                                          position="absolute"
                                          left="6%"
                                          bottom="0%"
                                          m="auto"
                                        />
                                      </Box>
                                      <Image
                                        src="images/img_vector_deep_orange_300.svg"
                                        h="13px"
                                        position="absolute"
                                        left="41%"
                                        bottom="1%"
                                        m="auto"
                                      />
                                    </Box>
                                    <Flex
                                      h="108px"
                                      bgImage="url(/images/img_group_53.svg)"
                                      bgSize="cover"
                                      bgRepeat="no-repeat"
                                      w="13%"
                                      direction="column"
                                      align="start"
                                      justify="flex-end"
                                      position="absolute"
                                      bottom="6%"
                                      right="39%"
                                      p="7px"
                                      m="auto"
                                    >
                                      <Image
                                        src="images/img_vector_gray_400_11x5.svg"
                                        h="11px"
                                        mt="54px"
                                        mb="26px"
                                      />
                                    </Flex>
                                  </Box>
                                  <Flex
                                    gap="6px"
                                    w="40%"
                                    justify="center"
                                    align="center"
                                    position="absolute"
                                    right="16%"
                                    bottom="0px"
                                    top="0px"
                                    h="100%"
                                    m="auto"
                                  >
                                    <Image
                                      src="images/img_xmlid_56.svg"
                                      h="30px"
                                    />
                                    <Flex
                                      h="67px"
                                      gap="26px"
                                      bgImage="url(/images/img_group_56.svg)"
                                      bgSize="cover"
                                      bgRepeat="no-repeat"
                                      w="61%"
                                      direction="column"
                                      justify="flex-end"
                                      p="5px"
                                    >
                                      <Image
                                        src="images/img_vector_gray_400_11x5.svg"
                                        h="1px"
                                        mt="11px"
                                        mr="60px"
                                      />
                                      <Flex
                                        ml="55px"
                                        w="10%"
                                        justify="flex-end"
                                        align="start"
                                      >
                                        <Image
                                          src="images/img_vector_gray_400_6x2.svg"
                                          h="6px"
                                          mt="6px"
                                        />
                                        <Image
                                          src="images/img_vector_black_900_5x1.svg"
                                          h="5px"
                                          mt="13px"
                                        />
                                        <Image
                                          src="images/img_vector_black_900_6x1.svg"
                                          h="6px"
                                          mt="12px"
                                        />
                                        <Image
                                          src="images/img_vector_gray_400_10x1.svg"
                                          h="10px"
                                          mb="8px"
                                        />
                                      </Flex>
                                    </Flex>
                                  </Flex>
                                </Box>
                                <Flex
                                  h="44px"
                                  bgImage="url(/images/img_group_61.svg)"
                                  bgSize="cover"
                                  bgRepeat="no-repeat"
                                  w="14%"
                                  direction="column"
                                  align="start"
                                  position="absolute"
                                  top="21%"
                                  right="35%"
                                  p="2px"
                                  m="auto"
                                >
                                  <Image
                                    src="images/img_vector_gray_800_01_1x1.svg"
                                    h="2px"
                                    mt="8px"
                                  />
                                  <Flex
                                    mb="7px"
                                    gap="7px"
                                    w="84%"
                                    direction="column"
                                    align="start"
                                  >
                                    <Flex
                                      w="100%"
                                      justify="space-between"
                                      align="start"
                                    >
                                      <Flex
                                        h="9px"
                                        bgImage="url(/images/img_group_77.svg)"
                                        bgSize="cover"
                                        bgRepeat="no-repeat"
                                        w="9px"
                                        direction="column"
                                        align="end"
                                        justify="flex-end"
                                        p="2px"
                                      >
                                        <Image
                                          src="images/img_vector_red_400.svg"
                                          h="1px"
                                          w="1px"
                                        />
                                      </Flex>
                                      <Image
                                        src="images/img_vector_gray_800_01_2x5.svg"
                                        h="2px"
                                      />
                                    </Flex>
                                    <Flex
                                      ml="4px"
                                      gap="8px"
                                      w="40%"
                                      align="start"
                                    >
                                      <Image
                                        src="images/img_vector_red_400.svg"
                                        h="1px"
                                        w="1px"
                                      />
                                      <Image
                                        src="images/img_vector_red_400_3x3.svg"
                                        h="3px"
                                        w="3px"
                                      />
                                    </Flex>
                                  </Flex>
                                </Flex>
                              </Box>
                              <Image
                                src="images/img_vector_deep_orange_300_9x3.svg"
                                h="9px"
                                position="absolute"
                                top="29%"
                                right="0px"
                                left="0px"
                                m="auto"
                              />
                              <Flex
                                h="41px"
                                pr="3px"
                                bgImage="url(/images/img_group_64.svg)"
                                bgSize="cover"
                                bgRepeat="no-repeat"
                                w="19%"
                                direction="column"
                                position="absolute"
                                bottom="26%"
                                right="26%"
                                py="3px"
                                m="auto"
                              >
                                <Flex
                                  mr="36px"
                                  gap="6px"
                                  w="30%"
                                  direction="column"
                                  align="end"
                                >
                                  <Image
                                    src="images/img_vector_gray_400_4x8.svg"
                                    h="4px"
                                  />
                                  <Image
                                    src="images/img_vector_gray_400.svg"
                                    h="12px"
                                    mr="3px"
                                    w="13px"
                                  />
                                </Flex>
                                <Flex
                                  ml="49px"
                                  w="4%"
                                  justify="flex-end"
                                  align="start"
                                  my="3px"
                                >
                                  <Image
                                    src="images/img_vector_black_900_3x7.svg"
                                    h="2px"
                                    w="1px"
                                  />
                                  <Image
                                    src="images/img_vector_black_900_5x1.svg"
                                    h="3px"
                                  />
                                </Flex>
                              </Flex>
                            </Box>
                            <Image
                              src="images/img_vector_gray_400_37x9.svg"
                              h="37px"
                              position="absolute"
                              bottom="32%"
                              right="25%"
                              m="auto"
                            />
                          </Box>
                          <Flex
                            w="16%"
                            direction="column"
                            align="start"
                            position="absolute"
                            right="34%"
                            bottom="0px"
                            top="0px"
                            h="100%"
                            m="auto"
                          >
                            <Image
                              src="images/img_vector_gray_800_01_23x35.svg"
                              h="23px"
                            />
                            <Image
                              src="images/img_vector_gray_50_02.svg"
                              h="1px"
                              mt="5px"
                              w="2px"
                            />
                            <Flex
                              mt="14px"
                              ml="22px"
                              gap="9px"
                              w="52%"
                              justify="flex-end"
                              align="end"
                            >
                              <Image
                                src="images/img_vector_gray_500_02.svg"
                                h="35px"
                                mb="5px"
                              />
                              <Image
                                src="images/img_vector_gray_500_02_46x9.svg"
                                h="46px"
                              />
                            </Flex>
                            <Image
                              src="images/img_vector_blue_gray_100_02.svg"
                              h="17px"
                              mt="26px"
                            />
                          </Flex>
                        </Box>
                        <Image
                          src="images/img_vector_gray_800_01_24x16.svg"
                          h="24px"
                          position="absolute"
                          top="21%"
                          right="37%"
                          m="auto"
                        />
                      </Box>
                      <Image
                        src="images/img_vector_gray_50_02_3x9.svg"
                        h="3px"
                        position="absolute"
                        top="28%"
                        right="41%"
                        m="auto"
                      />
                      <Flex
                        w="13%"
                        justify="center"
                        align="start"
                        position="absolute"
                        bottom="30%"
                        right="16%"
                        m="auto"
                      >
                        <Flex
                          h="9px"
                          mt="4px"
                          bgImage="url(/images/img_group_68.svg)"
                          bgSize="cover"
                          bgRepeat="no-repeat"
                          w="68%"
                          direction="column"
                          align="start"
                        >
                          <Image
                            src="images/img_vector_gray_400_10x1.svg"
                            h="2px"
                            w="2px"
                          />
                          <Image
                            src="images/img_vector_gray_400_10x1.svg"
                            h="3px"
                            mb="3px"
                            w="4px"
                          />
                        </Flex>
                        <Image
                          src="images/img_vector_black_900_4x5.svg"
                          h="4px"
                        />
                      </Flex>
                    </Box>
                    <Flex
                      gap="24px"
                      w="11%"
                      justify="center"
                      align="start"
                      position="absolute"
                      bottom="22%"
                      right="15%"
                      m="auto"
                    >
                      <Box h="16px" mt="3px" bg="black.900" w="1px" />
                      <Image
                        src="images/img_vector_black_900.svg"
                        h="6px"
                        w="6px"
                      />
                    </Flex>
                  </Box>
                  <Flex
                    gap="19px"
                    w="11%"
                    direction="column"
                    align="end"
                    position="absolute"
                    bottom="20%"
                    right="24%"
                    m="auto"
                  >
                    <Flex w="100%" justify="space-between" align="start">
                      <Box h="25px" bg="gray.400" w="3px" />
                      <Image
                        src="images/img_vector_gray_400_5x16.svg"
                        h="3px"
                        w="3px"
                      />
                    </Flex>
                    <Box h="20px" bg="black.900" w="5px" />
                  </Flex>
                  <Image
                    src="images/img_vector_gray_400_6x7.svg"
                    h="6px"
                    w="7px"
                    position="absolute"
                    top="40%"
                    right="35%"
                    m="auto"
                  />
                  <Center
                    h="3px"
                    bgImage="url(/images/img_vector_red_400.svg)"
                    bgSize="cover"
                    bgRepeat="no-repeat"
                    w="3px"
                    position="absolute"
                    top="29%"
                    right="40%"
                    m="auto"
                  >
                    <Image
                      src="images/img_vector_red_400_1x1.svg"
                      h="1px"
                      w="1px"
                    />
                  </Center>
                </Box>
                <Image
                  src="images/img_vector_gray_400_10x1.svg"
                  h="5px"
                  mb="75px"
                  mr="98px"
                  position="absolute"
                  ml="auto"
                  mt="auto"
                />
                <Image
                  src="images/img_vector_gray_400_5x2.svg"
                  h="5px"
                  mb="67px"
                  mr="69px"
                  position="absolute"
                  ml="auto"
                  mt="auto"
                />
                <Image
                  src="images/img_group_blue_300_59x79.svg"
                  h="59px"
                  mt="50px"
                  ml="5px"
                  position="absolute"
                />
                <Image
                  src="images/img_group_gray_600_01.svg"
                  h="36px"
                  mt="4px"
                  ml="90px"
                  position="absolute"
                />
                <Image
                  src="images/img_vector_deep_orange_400.svg"
                  h="52px"
                  mt="14px"
                  mr="13px"
                  position="absolute"
                  ml="auto"
                />
                <Flex
                  mt="19px"
                  mr="20px"
                  gap="10px"
                  w="20%"
                  direction="column"
                  align="end"
                  position="absolute"
                  ml="auto"
                >
                  <Flex w="95%" justify="space-between" align="start">
                    <Image
                      src="images/img_vector_white_a700_1x36.svg"
                      h="1px"
                      mt="4px"
                    />
                    <Image src="images/img_vector_white_a700.svg" h="12px" />
                  </Flex>
                  <Image src="images/img_vector_white_a700_1x35.svg" h="1px" />
                </Flex>
                <Flex
                  mt="30px"
                  mr="21px"
                  w="19%"
                  direction="column"
                  align="start"
                  position="absolute"
                  ml="auto"
                >
                  <Image src="images/img_vector_white_a700_1x34.svg" h="1px" />
                  <Image
                    src="images/img_vector_white_a700_1x35.svg"
                    h="1px"
                    mt="4px"
                    ml="4px"
                  />
                </Flex>
              </Box>
              <Flex
                w="76%"
                direction="column"
                align="end"
                position="absolute"
                top="12%"
                right="9%"
                m="auto"
              >
                <Image
                  src="images/img_vector_white_a700_4x4.svg"
                  h="4px"
                  w="4px"
                />
                <Image
                  src="images/img_group_blue_gray_900_02_94x228.svg"
                  h="94px"
                  mt="4px"
                />
              </Flex>
            </Box>
          </Flex>
        </Container>
      </Flex>
      <Container
        mt="100px"
        w="100%"
        display="flex"
        flexDirection="row"
        justifyContent="flex-start"
        maxW="1280px"
        px="0px"
      >
        <Flex w="100%" justify="space-between" align="center">
          <Image src="images/img_image_521x510.png" h="521px" />
          <Flex direction="column" align="start">
            <Flex gap="10px" w="100%" direction="column" align="start">
              <Heading size="xl" as="h3">
                Apply As Instructor
              </Heading>
              <Text lineHeight="30px">
                Teaching is a vital and admirable career. As such, it comes with
                quite a bit of responsibility, both in practice and in
                preparation with many skills required to be a teacher. The
                following steps provide a general breakdown of the requirements
                for teachers:
              </Text>
            </Flex>
            <Flex mt="35px" gap="30px" w="59%" align="start">
              <Flex gap="13px" w="56%" direction="column" align="center">
                <Text color="red.300" fontWeight={500}>
                  Instructor Requirements
                </Text>
                <Box h="1px" bg="red.300" boxShadow="xl" w="100%" />
              </Flex>
              <Text fontWeight={500}>Instructor Rules</Text>
            </Flex>
            <Flex mt="26px" gap="34px" w="48%" direction="column" align="start">
              <Flex w="100%" direction="column" align="start">
                <Flex gap="10px" w="78%" align="start">
                  <Box
                    h="10px"
                    mt="3px"
                    bg="red.300"
                    w="10px"
                    borderRadius="50%"
                  />
                  <Text color="gray.900">An undergraduate degree</Text>
                </Flex>
                <Flex mt="19px" gap="10px" w="100%" align="start">
                  <Box
                    h="10px"
                    mt="3px"
                    bg="red.300"
                    w="10px"
                    borderRadius="50%"
                  />
                  <Text color="gray.900">
                    Participate in supervised teaching
                  </Text>
                </Flex>
                <Flex mt="20px" gap="10px" w="68%" align="start">
                  <Box
                    h="10px"
                    mt="3px"
                    bg="red.300"
                    w="10px"
                    borderRadius="50%"
                  />
                  <Text color="gray.900">State teaching license</Text>
                </Flex>
                <Flex mt="20px" gap="10px" w="74%" align="start">
                  <Box
                    h="10px"
                    mt="3px"
                    bg="red.300"
                    w="10px"
                    borderRadius="50%"
                  />
                  <Text color="gray.900">Pursue graduate studies</Text>
                </Flex>
              </Flex>
              <Button
                variant="fill"
                fontWeight={500}
                minW="143px"
                borderRadius="10px"
              >
                Apply Now
              </Button>
            </Flex>
          </Flex>
        </Flex>
      </Container>
      <Container
        mt="105px"
        w="100%"
        display="flex"
        flexDirection="row"
        justifyContent="center"
        maxW="1060px"
        px="0px"
      >
        <Flex gap="64px" w="100%" direction="column" align="center">
          <Heading
            size="2xl"
            as="h1"
            fontFamily="Metropolis"
            textAlign="center"
          >
            How to apply to join as instructor
          </Heading>
          <Flex
            bg="white.A700"
            boxShadow="lg"
            w="100%"
            p="8px"
            borderRadius="20px"
          >
            <Flex mt="7px" bg="white.A700" w="100%">
              <Image src="images/img_bg.png" w="100%" borderRadius="20px" />
            </Flex>
          </Flex>
        </Flex>
      </Container>
      <Footer1
        mt="100px"
        flexDirection="column"
        display="flex"
        w="100%"
        alignItems="center"
        justifyContent="center"
      />
    </Flex>
  );
}
